import { Resource, TrackMeta } from '../types';

export const resources: Resource[] = [
  {
    id: 1,
    track: 'fundamentos',
    source: 'Harvard / edX',
    title: 'CS50: Introduction to Computer Science',
    desc: 'O melhor curso gratuito de introdução à ciência da computação. Cobre C, Python, SQL e JavaScript.',
    link: 'https://cs50.harvard.edu/x',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'en',
  },
  {
    id: 2,
    track: 'fundamentos',
    source: 'freeCodeCamp',
    title: 'Responsive Web Design Certification',
    desc: 'HTML e CSS do zero com projetos práticos. Certificado gratuito ao concluir.',
    link: 'https://www.freecodecamp.org/learn',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'en',
  },
  {
    id: 3,
    track: 'fundamentos',
    source: 'The Odin Project',
    title: 'Foundations Path',
    desc: 'Fundamentos de desenvolvimento web com projetos reais e comunidade ativa no Discord.',
    link: 'https://www.theodinproject.com/paths/foundations',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'en',
  },
  {
    id: 4,
    track: 'fundamentos',
    source: 'Curso em Vídeo',
    title: 'Algoritmos e Lógica de Programação',
    desc: 'Curso em português do professor Gustavo Guanabara. Ideal para iniciantes absolutos.',
    link: 'https://www.cursoemvideo.com/cursos/',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'pt',
  },
  {
    id: 5,
    track: 'web',
    source: 'MDN Web Docs',
    title: 'Guia completo de HTML & CSS',
    desc: 'Documentação oficial e referência definitiva para tecnologias web. Essencial ter no bookmark.',
    link: 'https://developer.mozilla.org/pt-BR/docs/Learn',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'pt',
  },
  {
    id: 6,
    track: 'web',
    source: 'JavaScript.info',
    title: 'The Modern JavaScript Tutorial',
    desc: 'Tutorial completo e atualizado de JavaScript moderno. Do básico a tópicos avançados.',
    link: 'https://javascript.info',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'en',
  },
  {
    id: 7,
    track: 'web',
    source: 'React Docs',
    title: 'React — Documentação Oficial',
    desc: 'A documentação oficial do React com tutoriais interativos e projetos guiados.',
    link: 'https://react.dev/learn',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'en',
  },
  {
    id: 8,
    track: 'web',
    source: 'freeCodeCamp',
    title: 'JavaScript Algorithms and Data Structures',
    desc: 'Certificação focada em JavaScript puro. Algoritmos, ES6 e programação funcional.',
    link: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'en',
  },
  {
    id: 9,
    track: 'backend',
    source: 'Cursa',
    title: 'Introdução ao Node.js',
    desc: 'Curso de Node para Iniciantes da Cursa com Certificado ao final do curso.',
    link: 'https://cursa.com.br/home/course/curso-de-node-js-gr%C3%A1tis/91',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'pt',
  },
  {
    id: 10,
    track: 'backend',
    source: 'W3Schools',
    title: 'Plataforma Multidisciplinar',
    desc: 'Vários cursos de diversas linguagens e conhecimentos.',
    link: 'https://www.w3schools.com/',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'en',
  },
  {
    id: 11,
    track: 'backend',
    source: 'PostgreSQL Docs',
    title: 'PostgreSQL Tutorial',
    desc: 'Aprenda banco de dados relacional com o banco mais popular do mercado.',
    link: 'https://www.postgresql.org/docs/current/tutorial.html',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'en',
  },
  {
    id: 12,
    track: 'backend',
    source: 'FullStackOpen',
    title: 'Full Stack Open — University of Helsinki',
    desc: 'Desenvolvimento full stack moderno com React, Node e MongoDB. Gratuito e certificado.',
    link: 'https://fullstackopen.com/ptbr/',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 3,
    lang: 'pt',
  },
  {
    id: 13,
    track: 'ferramentas',
    source: 'Git SCM',
    title: 'Pro Git Book',
    desc: 'Livro oficial do Git, disponível online e grátis. Tudo que você precisa sobre versionamento.',
    link: 'https://git-scm.com/book/pt-br/v2',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'pt',
  },
  {
    id: 14,
    track: 'ferramentas',
    source: 'GitHub',
    title: 'GitHub Skills',
    desc: 'Cursos interativos do GitHub. Aprenda Git, Actions e Codespaces no ambiente real.',
    link: 'https://skills.github.com',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 1,
    lang: 'en',
  },
  {
    id: 15,
    track: 'ferramentas',
    source: 'Vercel Docs',
    title: 'Deploy com Next.js na Vercel',
    desc: 'Documentação oficial para hospedar projetos Next.js gratuitamente na Vercel.',
    link: 'https://vercel.com/docs',
    badge: 'free',
    badgeLabel: 'Grátis',
    level: 2,
    lang: 'en',
  },
];

export const tracks: TrackMeta[] = [
  {
    id: 'fundamentos',
    label: 'Fundamentos',
    number: '01',
    color: 'track-green',
    accent: '#00D084',
  },
  {
    id: 'web',
    label: 'Web & Frontend',
    number: '02',
    color: 'track-purple',
    accent: '#6C63FF',
  },
  {
    id: 'backend',
    label: 'Back-end & Full Stack',
    number: '03',
    color: 'track-orange',
    accent: '#FF6B35',
  },
  {
    id: 'ferramentas',
    label: 'Ferramentas & Deploy',
    number: '04',
    color: 'track-green',
    accent: '#00D084',
  },
];